server:
  port: 80
spring:
  application:
    name: consumer-openfeign-80

eureka:
  client:
    register-with-eureka: true #注册到eureka
    fetch-registry: true #检索服务信息
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka, http://eureka9002.com:9002/eureka

#openfeign日志调试
#logging:
#  level:
#    cn.zero.commerce.service.MemberOpenFeignService: debug


#配置超时
#ribbon:
#  #openfeign默认支持ribbon
#  #设置超时时间
#  ReadTimeOut: 8000 #建立连接从提供方获取资源的全部时间
#  ConnectionTimeOut: 8000 #两端连接所用时间