server:
  port: 10000
spring:
  application:
    name: member-provider-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_commerce_db?&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: diory2021zero
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.zero.commerce.entity

eureka:
  client:
    register-with-eureka: true #注册到eureka
    fetch-registry: true #检索服务信息
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka, http://eureka9002.com:9002/eureka
  #instance:
    #lease-renewal-interval-in-seconds: 1 #发送心跳时间间隔/秒
    #lease-expiration-duration-in-seconds: 10 #服务端收到最后一次心跳的等待时间